name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Fetch KernelSU-SuSFS
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs-dev

      - name: Run Build build script
        run: |
          export KBUILD_BUILD_USER=mahiro
          export KBUILD_BUILD_HOST=android-build
          source build.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Upload Kernel
        uses: actions/upload-artifact@main
        with:
          name: standard-artifact
          path: ${{ env.ZIPNAME }}

      - name: Create Telegram caption
        run: |
          BUILD_DATE="$(date '+%H:%M %d/%m/%Y')"
          HEAD="$(git rev-parse HEAD)"
          HEAD_COMMIT="https://github.com/rinnsakaguchi/msm-4.14/commit/$HEAD"
          echo -e "${BUILD_DATE}\n\n${HEAD_COMMIT}" > caption.txt

      - name: Upload to Telegram
        run: |
          caption=$(<caption.txt)
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F document=@"${{ env.ZIPNAME }}" \
          -F caption="${caption}"
