name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Run standard build script
        run: |
          export KBUILD_BUILD_USER=nobody
          export KBUILD_BUILD_HOST=android-build
          source build.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

